# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Go@0
      inputs:
        command: 'test'
        arguments: '-v ./...'
    - task: Go@0
      inputs:
        command: 'build'
        arguments: '-o main'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/pkg*.xml'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'main'
        publishLocation: 'pipeline'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'cjt-dockerhub'
        repository: 'azure-devops/alauda-ci'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
